// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 179);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1789530325);
user_pref("browser.search.region", "PK");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":26,\"newElementCount\":0}");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "7c230511-a17c-466d-a8e8-c3faf6acd2a3");
user_pref("datareporting.dau.cachedUsageProfileID", "0d6766fb-1a4a-480b-ab7e-61ff4a221f45");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "155.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20260904071051");
user_pref("extensions.lastAppVersion", "155.0.1");
user_pref("extensions.lastPlatformVersion", "155.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"542185fb-c7e5-4016-a7c4-c65a5bd04393\",\"ipp-activator@mozilla.com\":\"bc212194-e45b-4212-a2f4-ee588d7bf185\",\"pictureinpicture@mozilla.org\":\"c8f9bd40-0e88-4934-a6c9-acd74c775c28\",\"addons-search-detection@mozilla.com\":\"76a8f578-2a6d-4fe1-a1d7-acac071d936d\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"b02d38e2-21ce-4f2f-9684-70467986be85\",\"default-theme@mozilla.org\":\"f4825d9d-b289-43f1-bcf3-9e2bef38d7e2\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "697b4605-e7f1-41fb-a37b-a5a875e2fb14");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("services.settings.base_attachments_url", "https://firefox.settings.services.mozilla.com/v2|https://firefox-settings-attachments.cdn.mozilla.net/");
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.startup.last_success", 1789530688);
user_pref("toolkit.telemetry.cachedClientID", "38b97b44-5738-4735-8ded-755054452e0e");
user_pref("toolkit.telemetry.cachedProfileGroupID", "00b5dc69-7105-4392-b67b-1ce19812f41a");
user_pref("toolkit.telemetry.previousBuildID", "20260904071051");
